{% set name = "jaraco.collections" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be570ef4f2e7290b757449395238fa63d70a9255574624e73c5ff9f1ee554721

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15
  run:
    - python
    - jaraco.text
    - jaraco.classes
    - six >=1.7.0

test:
  imports:
    - jaraco.collections

about:
  home: https://github.com/jaraco/jaraco.collections
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Models and classes to supplement the stdlib 'collections' module."
  doc_url: https://jaracocollections.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.collections

extra:
  recipe-maintainers:
    - carlodri
